"""empty message

Revision ID: 9a14994fb20f
Revises: 803c9758a5d8
Create Date: 2018-11-30 18:14:41.019933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a14994fb20f'
down_revision = '803c9758a5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slug', table_name='tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('slug', 'tag', ['slug'], unique=True)
    # ### end Alembic commands ###
